### ISSUE TITLE
喵崽调用方法

### ISSUE THREAD

**Issue by touchscale** [linxinrao/Shamrock#100]
在手机端部署并打开专业级接口后，电脑端如何进行调用

**Comment by RealHeart** [comment]
和qsign一样

**Comment by touchscale** [comment]
> 和qsign一样

![Screenshot_2023-10-14-20-50-57-398_moe.fuqiuluo.shamrock.jpg](https://github.com/linxinrao/Shamrock/assets/107158734/15bf090e-6bb6-42a7-b0e2-72679129998f)

**Comment by touchscale** [comment]
现在是这样的，手机开着移动数据和热点，电脑连接着手机热点

**Comment by RealHeart** [comment]
> 现在是这样的，手机开着移动数据和热点，电脑连接着手机热点

不知道，找的能连你手机的IP就行

**Comment by touchscale** [comment]
> > 现在是这样的，手机开着移动数据和热点，电脑连接着手机热点
> 
> 不知道，找的能连你手机的IP就行

{
    "status": "failed",
    "retcode": 10003,
    "data": {
        "url": "/sign",
        "error": "Lack of param uin"
    }
}
能成功访问了，但是提示缺少参数uin

**Comment by RealHeart** [comment]
![image](https://github.com/linxinrao/Shamrock/assets/24838944/0bcf56ad-0357-4bf8-829c-ed5dcd0217f0)

**Comment by touchscale** [comment]
> ![image](https://github.com/linxinrao/Shamrock/assets/24838944/0bcf56ad-0357-4bf8-829c-ed5dcd0217f0)
> 

不用加端口嘛

**Comment by touchscale** [comment]
![Screenshot_2023-10-14-22-23-19-804_moe.fuqiuluo.shamrock.jpg](https://github.com/linxinrao/Shamrock/assets/107158734/746397df-877e-4f8e-b536-13d90c4065d7)

![Screenshot_2023-10-14-22-23-15-359_moe.fuqiuluo.shamrock.jpg](https://github.com/linxinrao/Shamrock/assets/107158734/a376ce41-0740-4ba0-b87f-078869d73251)

**Comment by touchscale** [comment]
这是应用的配置状况，应该没配置错吧

**Comment by RealHeart** [comment]
> > ![image](https://github.com/linxinrao/Shamrock/assets/24838944/0bcf56ad-0357-4bf8-829c-ed5dcd0217f0)
> 
> 不用加端口嘛

加 5700

**Comment by touchscale** [comment]
> > > ![image](https://github.com/linxinrao/Shamrock/assets/24838944/0bcf56ad-0357-4bf8-829c-ed5dcd0217f0)
> > 
> > 不用加端口嘛
> 
> 加 5700

加了

**Comment by RealHeart** [comment]
> > > > ![image](https://github.com/linxinrao/Shamrock/assets/24838944/0bcf56ad-0357-4bf8-829c-ed5dcd0217f0)
> > > 
> > > 
> > > 不用加端口嘛
> > 
> > 
> > 加 5700
> 
> 加了

那我不知道，可能不支持icqq？
@fuqiuluo
