### ISSUE TITLE
feat: 群聊文件上传事件

### ISSUE THREAD

**Issue by RexQian** [linxinrao/Shamrock#102]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

在群聊中上传一个文本文件，希望能够接收到上传事件

目前的情况是会提示（开启了消息格式为CQ码)

WARN 不支持的Elem转消息段: 3

### 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by RealHeart** [comment]
f70f6dfec09077b1002b1319b3e5320a8a0471c7

#57

**Comment by fuqiuluo** [comment]
[群文件上传事件](https://linxinrao.github.io/Shamrock/event/notice.html#%E7%BE%A4%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)，最新的action构建包已经支持群文件事件。
