### ISSUE TITLE
bug: 机器人未在群内可执行发送消息接口

### ISSUE THREAD

**Issue by RealHeart** [linxinrao/Shamrock#111]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

当机器人未在群内可正确执行发送消息接口，且会返回消息ID

### 复现 Bug

`GET /send_group_message?group_id=******&message=Test`

## 系统信息

- Shamrock 版本: 1.0.5-dev
- Android 版本: 9
- 设备的制造商和型号: FydeOS
- 设备的 CPU 架构: x86_64

**Comment by fuqiuluo** [comment]
这个没办法处理
qq客户端的数据有缓存，没办法立即更新，执行是否在群后再发消息的判断

**Comment by RealHeart** [comment]
> 这个没办法处理
> qq客户端的数据有缓存，没办法立即更新，执行是否在群后再发消息的判断

日志显示 `code: 110 发送失败，你已被移出该群，清重新加群。`
