### ISSUE TITLE
bug: 发送群消息报错contact is not found

### ISSUE THREAD

**Issue by SlightDust** [linxinrao/Shamrock#114]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

最新两个Action，也就是基于 4ed74cb 和 64e53b3 构建的，调用send_group_msg接口都会返回 contact is not found  
`{"status":"failed","retcode":35000,"data":{},"message":"contact is not found","echo":""}`
![image](https://github.com/linxinrao/Shamrock/assets/53001305/2dbd0f2b-345a-4e50-a829-dcdbba478674)

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: Shamrock-v1.0.5-dev.64e53b3-all
- Android 版本: 12
- 设备的制造商和型号: Redmi K30 5G
- 设备的 CPU 架构: arm64

**Comment by SlightDust** [comment]
接口返回这个`contact is not found`，日志没有打印

**Comment by RealHeart** [comment]
应该是 获取群/好友列表 使用的是缓存数据的原因。

**Comment by fuqiuluo** [comment]
> 应该是 获取群/好友列表 使用的是缓存数据的原因。

每次请求都刷新群列表，会浪费资源
