### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by xichanggumeng** [linxinrao/Shamrock#115]
### 描述 Bug

xposed启动插件后，无论如何重启、重装，shamrock始终显示未激活。

### 复现 Bug

vmos虚拟机环境 
安卓 7.1.2 
xposed 
qq-8.9.83

## 系统信息

- Shamrock 版本: 1.0.5-dev
- Android 版本: 7.1.2
- 设备的制造商和型号: Redmi note 8 pro @ vmos pro
- 设备的 CPU 架构: arm-64

**Comment by fuqiuluo** [comment]
能否提供xposed日志？

**Comment by RealHeart** [comment]
是否在 Shamrock 应用未被杀死都情况下，重新启动QQ主程序

**Comment by xichanggumeng** [comment]
破案了，vmos的锅
经测试，vmos全系rom均不可
光速模拟器 Android10可以
