### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by JBNRZ** [linxinrao/Shamrock#119]
### 描述 Bug

当有新用户加入群聊时，会报 `不支持的灰条类型(JSON): 17`
![image](https://github.com/linxinrao/Shamrock/assets/76835191/a539155a-fb87-4ef8-9ffa-e5f2deeaa9b9)

### 复现 Bug

加入群聊

## 系统信息

- Shamrock 版本:  Shamrock-v1.0.5-dev.e55dcaf-all
- Android 版本:  12
- 设备的制造商和型号:  Mumu模拟器 HUAWEI MGA-AL00
- 设备的 CPU 架构:  x86_64

**Comment by JBNRZ** [comment]
可能是bug？我看文档里是已经支持了群成员增加的通知事件了

**Comment by fuqiuluo** [comment]
最新构建，暂时无法构建，正在加arm-v7a支持
