### ISSUE TITLE
bug: Xposed框架不支持

### ISSUE THREAD

**Issue by fuqiuluo** [linxinrao/Shamrock#123]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

请清晰地描述此 Bug 的具体表现，并提供错误日志。

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

安卓8.1才可以使用Lsposed，安卓9才能使用Lspatch，纯Xposed框架和EdXposed框架由于载入模块逻辑落后，无法支持Shamrock中Classloader替换写法，导致无法注入QQ。

## 系统信息

- Shamrock 版本: all
- Android 版本: all
- 设备的制造商和型号: all
- 设备的 CPU 架构: all

**Comment by zszcq** [comment]
咋说呢,我多年前的MIX2都是安卓9,目前正常运行Shamrock,低于安卓8的设备我觉得也不太合适拿来当机器人框架了

**Comment by RealHeart** [comment]
实际上 Dreamland 支持 Android 5.0-13

**Comment by fuqiuluo** [comment]
> 咋说呢,我多年前的MIX2都是安卓9,目前正常运行Shamrock,低于安卓8的设备我觉得也不太合适拿来当机器人框架了

还是可以跑的。
