### ISSUE TITLE
能否给个 Linux x64 服务器部署教程

### ISSUE THREAD

**Issue by TimeRainStarSky** [linxinrao/Shamrock#23]
按 Wiki 使用 redroid 安装 LSPosed 或 LSPatch 都失败了，能否给个详细教程

**Comment by fuqiuluo** [comment]
服务器安LSPOSED固然抽象

**Comment by fuqiuluo** [comment]
您为redroid安装arm64转译插件了吗？

**Comment by TimeRainStarSky** [comment]
> 服务器安LSPOSED固然抽象

所以怎么安装呢

**Comment by TimeRainStarSky** [comment]
> 您为redroid安装arm64转译插件了吗？

我看 redroid 上写是自带的，需要额外安装吗

**Comment by fuqiuluo** [comment]
实际上是不自带的，需要你手动安装。

**Comment by fuqiuluo** [comment]
建议使用云手机部署+内网穿透。
