### ISSUE TITLE
访问/send_packet接口可能导致QQ崩溃

### ISSUE THREAD

**Issue by callng** [linxinrao/Shamrock#28]
**Describe the bug**
RT，使用API`/send_packet`可能导致QQ异常退出。

**To Reproduce**
1. 打开专业级接口，重启QQ
2. 使用模块中定义的端口访问API`/send_packet`(访问方式：POST)
3. 多次访问该接口导致QQ崩溃或异常退出(正常返回JSON内容的data不为`null`)

**Expected behavior**
访问API`/send_packet`不会导致QQ崩溃或异常退出。

**Screenshots**
正常情况下
![2](https://github.com/linxinrao/Shamrock/assets/64207250/ce2d0a03-5d42-4ff3-a9db-1964880fe1d5)
异常情况下
![1](https://github.com/linxinrao/Shamrock/assets/64207250/d2a77056-142f-4513-8596-e261fdae9e92)

**Smartphone (please complete the following information):**
 - Device: 小米13U
 - OS: 安卓13 MIUI14
 - QQVersion: 8.9.80

**Additional context**
shamrock构建版本(cb11b54b625d41c7dc6dbdd955d5b6f22d32c742)

**Comment by fuqiuluo** [comment]
请提供错误日志

**Comment by callng** [comment]
**MSF.S.AppProcessManager**：
can not find com.tencent.mobileqq to receive msg to:ToServiceMsg msName:unknown ssoSeq:84255 appId:537178184 appSeq:57 sName:com.tencent.mobileqq.msf.service.MsfService uin:被省略 sCmd:SafeCenterSvr.CMD_FACE2FACE_FLAG_REQ t:480000 needResp:true needQuickSend:false strategy:0IsSupportRetryfalse from:FromServiceMsg msName:unknown ssoSeq:84255 failCode:1002 errorMsg:wait serverResp timeout uin:被省略serviceCmd:SafeCenterSvr.CMD_FACE2FACE_FLAG_REQ appId:537178184 appSeq:57

**SocketReaderNewtrue**：
socketEngine: 1socket hashCode: 0SocketReader(180) errorjava.net.SocketException: Socket is closed
socketEngine: 0socket hashCode: 0SocketReader(181) errorjava.net.SocketException: Socket is closed

LSP管理器中无任何日志输出，但是如果QQ崩溃退出后`com.tencent.mobileqq`进程就没了，只剩下`:MSF`进程了

![Screenshot_2023-09-24-10-55-57-676_github tornaco](https://github.com/linxinrao/Shamrock/assets/64207250/4f659264-bef2-41a6-b8d7-00516eb523fe)

**Comment by fuqiuluo** [comment]
无法定位问题修复....
