### ISSUE TITLE
增加文件发送与图片

### ISSUE THREAD

**Issue by Xiaolangs** [linxinrao/Shamrock#30]
希望可以增加图片与文件的发送

**Comment by fuqiuluo** [comment]
发生图片有的啊，发送文件没有而已。

**Comment by Xiaolangs** [comment]
> enhancement

是可以发送本地的图片吗。

**Comment by fuqiuluo** [comment]
```cqcode
[CQ:image,file=file:///path/to/1.jpg]
```
这样就可以啊。

**Comment by fuqiuluo** [comment]
> > enhancement
> 
> 是可以发送本地的图片吗？，怎么发送。 另外可以利用这个来支撑mirai的签名服务吗

对的，我们这里是允许作为签名服务器的，目前测试30多个人的号用shamrock签名，依旧稳定。

**Comment by Xiaolangs** [comment]
> > > enhancement
> > 
> > 
> > 是可以发送本地的图片吗？，怎么发送。 另外可以利用这个来支撑mirai的签名服务吗
> 
> 对的，我们这里是允许作为签名服务器的，目前测试30多个人的号用shamrock签名，依旧稳定。
是通过sign这个那个API吗。可以支持fix-protocol-version吗

**Comment by fuqiuluo** [comment]
可能会有兼容问题吧，qsign的一些服务api在shamrock不存在，你可以去`fix-protocol-version`反馈一下兼容。

**Comment by Xiaolangs** [comment]
> 可能会有兼容问题吧，qsign的一些服务api在shamrock不存在，你可以去`fix-protocol-version`反馈一下兼容。

目前你们是怎么使用，可以提供一下方案吗？

**Comment by fuqiuluo** [comment]
> > 可能会有兼容问题吧，qsign的一些服务api在shamrock不存在，你可以去`fix-protocol-version`反馈一下兼容。
> 
> 目前你们是怎么使用，可以提供一下方案吗？

oicq的那几个衍生项目支持，你可以加一下我们的群问一下。702991373。

**Comment by fuqiuluo** [comment]
#57
