### ISSUE TITLE
部分界面未适配深色模式

### ISSUE THREAD

**Issue by RealHeart** [linxinrao/Shamrock#32]
![Screenshot_2023-09-25-23-16-25-358_moe.fuqiuluo.shamrock.jpg](https://github.com/linxinrao/Shamrock/assets/24838944/c0754380-1cbc-4e41-b7cb-8720f855b57f)

**Comment by fuqiuluo** [comment]
界面写死了亮色模式，暗色没写

**Comment by fuqiuluo** [comment]
如果可以 尝试pr一份？
