### ISSUE TITLE
鉴权Token配置后没有作用

### ISSUE THREAD

**Issue by paulzzh** [linxinrao/Shamrock#35]
QQ 8.9.73
LSPosed 1.9.1
配置鉴权Token重启后仍然能直接访问敏感接口
![image](https://github.com/linxinrao/Shamrock/assets/28055560/82d3454f-0a1f-4cf8-ad52-681a0f9880db)
![image](https://github.com/linxinrao/Shamrock/assets/28055560/6ca6cb0f-a6ba-49a2-bf84-1258dcdc1d02)

**Comment by fuqiuluo** [comment]
https://github.com/linxinrao/Shamrock/actions/runs/6337373744
请使用该构建结果重新测试

**Comment by fuqiuluo** [comment]
请加群：758533243，跟踪后续问题。

**Comment by ayakasuki** [comment]
确实 
![image](https://github.com/linxinrao/Shamrock/assets/20859971/a62f45d8-1c38-4321-85be-9294db2ed7c7)
我是加了token的 但是无token也能发送信息和获取列表
![image](https://github.com/linxinrao/Shamrock/assets/20859971/477813fc-074e-4d57-95fd-79d7a03a55bc)
