### ISSUE TITLE
[Feature] 群文件功能支持

### ISSUE THREAD

**Issue by fuqiuluo** [linxinrao/Shamrock#57]
# 实现进程

- [x] 群文件上传事件，携带url
- [x] 上传群文件
- [x] 创建群文件夹
- [x] 删除群文件夹
- [x] 获取群文件系统信息
- [x] 获取群根目录文件列表
- [x] 获取群子目录文件列表
- [x] 获取群文件资源链接
- [x] 私聊文件事件
- [x] 上传私聊文件
- [x] ~来自我的设备文件事件~
- [x] ~上传我的设备文件~

## 扩展事件

- [x] ~文件上传进度上报~
- [x] ~文件类消息CQ码支持~

**Comment by jinyu2022** [comment]
请求添加 收到离线文件 接口

**Comment by fuqiuluo** [comment]
>  请求添加 收到离线文件 接口

已添加

**Comment by RexQian** [comment]
go-cqhttp 在发送群聊文件上传事件的时候 会提供下载的url 是否考虑支持

https://github.com/Mrs4s/go-cqhttp/blob/8607542f1e650d3f4df8aa0c313b5020ac265467/coolq/event.go#L110

```
bot.dispatchEvent("notice/group_upload", global.MSG{
				"group_id": m.GroupCode,
				"user_id":  m.Sender.Uin,
				"file": global.MSG{
					"id":    file.Path,
					"name":  file.Name,
					"size":  file.Size,
					"busid": file.Busid,
					"url":   c.GetGroupFileUrl(m.GroupCode, file.Path, file.Busid),
				},
			})
```

**Comment by fuqiuluo** [comment]
> go-cqhttp 在发送群聊文件上传事件的时候 会提供下载的url 是否考虑支持
> 
> https://github.com/Mrs4s/go-cqhttp/blob/8607542f1e650d3f4df8aa0c313b5020ac265467/coolq/event.go#L110
> 
> ```
> bot.dispatchEvent("notice/group_upload", global.MSG{
> 				"group_id": m.GroupCode,
> 				"user_id":  m.Sender.Uin,
> 				"file": global.MSG{
> 					"id":    file.Path,
> 					"name":  file.Name,
> 					"size":  file.Size,
> 					"busid": file.Busid,
> 					"url":   c.GetGroupFileUrl(m.GroupCode, file.Path, file.Busid),
> 				},
> 			})
> ```

好的

**Comment by fuqiuluo** [comment]
> go-cqhttp 在发送群聊文件上传事件的时候 会提供下载的url 是否考虑支持
> 
> https://github.com/Mrs4s/go-cqhttp/blob/8607542f1e650d3f4df8aa0c313b5020ac265467/coolq/event.go#L110
> 
> ```
> bot.dispatchEvent("notice/group_upload", global.MSG{
> 				"group_id": m.GroupCode,
> 				"user_id":  m.Sender.Uin,
> 				"file": global.MSG{
> 					"id":    file.Path,
> 					"name":  file.Name,
> 					"size":  file.Size,
> 					"busid": file.Busid,
> 					"url":   c.GetGroupFileUrl(m.GroupCode, file.Path, file.Busid),
> 				},
> 			})
> ```

https://github.com/linxinrao/Shamrock/commit/6a337e89ada2390600dd8bb467216a7893fdaff4 已实现

**Comment by RexQian** [comment]
> > go-cqhttp 在发送群聊文件上传事件的时候 会提供下载的url 是否考虑支持
> > https://github.com/Mrs4s/go-cqhttp/blob/8607542f1e650d3f4df8aa0c313b5020ac265467/coolq/event.go#L110
> > ```
> > bot.dispatchEvent("notice/group_upload", global.MSG{
> > 				"group_id": m.GroupCode,
> > 				"user_id":  m.Sender.Uin,
> > 				"file": global.MSG{
> > 					"id":    file.Path,
> > 					"name":  file.Name,
> > 					"size":  file.Size,
> > 					"busid": file.Busid,
> > 					"url":   c.GetGroupFileUrl(m.GroupCode, file.Path, file.Busid),
> > 				},
> > 			})
> > ```
> 
> [6a337e8](https://github.com/linxinrao/Shamrock/commit/6a337e89ada2390600dd8bb467216a7893fdaff4) 已实现

url默认返回的地址是https的 实际上因为返回的是ip而不是域名 即证书和域名不匹配 导致没法直接使用

需要在下载的时候 忽略https证书 或者 将https转换为http (http也能用)

go-cqhttp提供的是http的地址 具体处理逻辑没看过

**Comment by fuqiuluo** [comment]
bot端忽略证书即可

**Comment by fuqiuluo** [comment]
QQ客户端请求用的是https

**Comment by RexQian** [comment]
> QQ客户端请求用的是https

OK
