### ISSUE TITLE
［Feature］完整支持私聊事件

### ISSUE THREAD

**Issue by SoulGI** [linxinrao/Shamrock#66]
在向机器人发起私聊时，机器人若有回应则会产生报错，似乎是将私聊发起人的QQ号当成了QQ群号
![IMG_20231010_215010](https://github.com/linxinrao/Shamrock/assets/51896050/cde03da7-369a-4262-9a59-393051e22ae4)
同时QQ本体也会出现一个群号为私聊发起人的QQ号的不存在的群聊
![IMG_20231010_215107](https://github.com/linxinrao/Shamrock/assets/51896050/9b936d1b-0d47-4ad3-b924-ed7802c03959)

**Comment by SoulGI** [comment]
个人不是很理解“快速操作”是什么意思
机器人是通过被动websocket连接到框架上的
我发的那个“这是私聊”，而后面的“是什么是”是触发了机器人自己的插件，由机器人自己发送的语句
除此之外本人没有再做更多的操作了

**Comment by fuqiuluo** [comment]
无法复现！

**Comment by fuqiuluo** [comment]
请提供机器人框架项目地址

**Comment by SoulGI** [comment]
机器人的项目是这个https://github.com/Kyomotoi/ATRI

**Comment by SoulGI** [comment]
如果需要更多环境描述的话，是用一个已经root过并且已刷入Lsposed的平板运行Shamrock，机器人由于在Termux部署出了点问题，所以是跑在电脑上，电脑和平板处在同一局域网，然后平板设定被动Websocket地址到"[电脑的局域网ip]:[我在机器人框架中指定的端口号]/onebot/v11/ws"，机器人框架配置文件config.yml设定host为0.0.0.0，port为上面websocket地址一样的端口号

**Comment by fuqiuluo** [comment]
[ATRI](https://github.com/Kyomotoi/ATRI)基于nonebot2，无法定位问题原因？

**Comment by fuqiuluo** [comment]
能否把ATRI的日志也发一下

**Comment by Kyomotoi** [comment]
> 个人不是很理解“快速操作”是什么意思 机器人是通过被动websocket连接到框架上的 我发的那个“这是私聊”，而后面的“是什么是”是触发了机器人自己的插件，由机器人自己发送的语句 除此之外本人没有再做更多的操作了

https://github.com/Kyomotoi/ATRI/blob/1a4c98d14f5b436b6f7e240c99980c5d5c315490/ATRI/plugins/kimo/__init__.py#L23
这是对应功能的实现 @fuqiuluo
