### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Well2333** [linxinrao/Shamrock#68]
**警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 确保您使用的是 [最新开发版本][actions-link] 的 Shamrock.
- [x] 确保您的问题尚未在 Issues 列表中提出.
- [x] 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

目前[最新 Action 版本](https://github.com/linxinrao/Shamrock/actions/runs/6472328400)的任意带有校验的文本框均无法进行任何修改，包括删除内容
![d992e6eb3499ec32319833a902ac145c](https://github.com/linxinrao/Shamrock/assets/40534114/222661a7-6447-4bf5-b9bf-b3650dfc2660)
![0a108f48f07cea694472304b654e95b7](https://github.com/linxinrao/Shamrock/assets/40534114/3c892bdb-d165-4db9-a2b2-f53911eab034)

## 系统信息

- Shamrock 版本: https://github.com/linxinrao/Shamrock/actions/runs/6472328400
- Android 版本: 12
- 设备的制造商和型号: Redmi K50
- 设备的 CPU 架构: arm64

[actions-link]: https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml

**Comment by fuqiuluo** [comment]
这个MD组件判断输入不合法之后就禁止输入了
