### ISSUE TITLE
feat: Sk对nonebot的支持

### ISSUE THREAD

**Issue by contr4l** [linxinrao/Shamrock#74]
**警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 确保您使用的是 [最新开发版本][actions-link] 的 Shamrock.
- [x] 确保您的功能请求尚未在 Issues 列表中提出.
- [x] 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

希望增加从Shamrock到nonebot或nonebot2的支持，如果在文档中能加入部分样例就更好了。

### 实现方法

无

[actions-link]: https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml

**Comment by fuqiuluo** [comment]
NoneBot2支持OneBot11，理论上 Shamrock支持NoneBot2或者1

**Comment by fuqiuluo** [comment]
目前的确缺少一些文档，可以等一下NoneBot用户来PR一下
