### ISSUE TITLE
bug: errorjson: cannot unmarshal string into Go struct field MessageQQ.echo of type int64

### ISSUE THREAD

**Issue by ShiaBox** [linxinrao/Shamrock#75]
### 描述 Bug

CQ码对接ob11的正向ws项目时返回如下错误。
`errorjson: cannot unmarshal string into Go struct field MessageQQ.echo of type int64`

### 复现 Bug

打开主动WS开关
对接客户端[SealDice](https://github.com/sealdice/sealdice-core)时提示`errorjson: cannot unmarshal array into Go struct field MessageQQ.message of type string`
然后打开消息格式为CQ码的开关时，变为`errorjson: cannot unmarshal string into Go struct field MessageQQ.echo of type int64`

## 系统信息

- Shamrock 版本:1.0.3
- Android 版本:9
- 设备的制造商和型号:逍遥模拟器
- 设备的 CPU 架构:x86-64

**Comment by fuqiuluo** [comment]
添加一个识别操作，根据请求提交的```
echo
```的类型去决定返回的```
echo
```。
