### ISSUE TITLE
feat: 请求文档添加响应示例

### ISSUE THREAD

**Issue by jinyu2022** [linxinrao/Shamrock#78]
**警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 确保您使用的是 [最新开发版本][actions-link] 的 Shamrock.
- [x] 确保您的功能请求尚未在 Issues 列表中提出.
- [ ] 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

请求给文档的响应添加示例

![image](https://github.com/linxinrao/Shamrock/assets/96060102/5a52de3f-a2e3-4372-bd13-f00c267f8c46)

### 实现方法

我注意到文档用的是theme-hope，那么可以开启选项卡功能

[actions-link]: https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml

**Comment by jinyu2022** [comment]
> 这个 `响应` 是包括 `接口` 和 `事件` 吗

恩，作为用户，我不嫌多，越详细越好

**Comment by RealHeart** [comment]
实现方式:

![image](https://github.com/linxinrao/Shamrock/assets/24838944/01e95eaf-f919-42fd-8460-290d3d484556)

预计 13-14 日 修改完毕

**Comment by jinyu2022** [comment]
> 实现方式:
> 
> ![image](https://user-images.githubusercontent.com/24838944/274488720-01e95eaf-f919-42fd-8460-290d3d484556.png)
> 
> 预计 13-14 日 修改完毕

不建议删除表格，表格有事也很有用，很直观

**Comment by RealHeart** [comment]
![image](https://github.com/linxinrao/Shamrock/assets/24838944/0bb2314a-d97e-4f64-87ea-e39f53ddaffb)

**Comment by RealHeart** [comment]
目前使用的是 [代码块分组](https://theme-hope.vuejs.press/zh/guide/markdown/code-tabs.html)，内部只能放代码块内容。
如果使用 [选项卡](https://theme-hope.vuejs.press/zh/guide/markdown/tabs.html)，内部会存在冗余空间，且体积较大。

**Comment by RealHeart** [comment]
两种方案
一种如上图，字段和示例分开写

另外一种把表格用源码方式表示

```markdowm
| 字段          | 类型   | 必须 | 说明                     |
| ------------- | ------ | ---- | ------------------------ |
| nickname      | string | 是   | 昵称                     |
| company       | string | 是   | 公司                     |
| email         | string | 是   | 邮箱                     |
| college       | string | 是   | 大学                     |
| personal_note | string | 是   | 个人备注                 |
| age           | int32  | 否   | 年龄                     |
| birthday      | string | 否   | 生日（格式：YYYY-MM-DD） |
```

**Comment by jinyu2022** [comment]
> 目前使用的是 [代码块分组](https://theme-hope.vuejs.press/zh/guide/markdown/code-tabs.html)，内部只能放代码块内容。 如果使用 [选项卡](https://theme-hope.vuejs.press/zh/guide/markdown/tabs.html)，内部会存在冗余空间，且体积较大。

内部什么冗余空间？

**Comment by RealHeart** [comment]
> > 目前使用的是 [代码块分组](https://theme-hope.vuejs.press/zh/guide/markdown/code-tabs.html)，内部只能放代码块内容。 如果使用 [选项卡](https://theme-hope.vuejs.press/zh/guide/markdown/tabs.html)，内部会存在冗余空间，且体积较大。
> 
> 内部什么冗余空间？

![Screenshot_2023-10-12-14-52-15-568_com.microsoft.emmx-edit.jpg](https://github.com/linxinrao/Shamrock/assets/24838944/0685b639-b66e-43ac-98d0-ae6172ec951a)

**Comment by jinyu2022** [comment]
哦，我瞅瞅能不能改css，这个应该改改css就行

**Comment by jinyu2022** [comment]
> 目前使用的是 [代码块分组](https://theme-hope.vuejs.press/zh/guide/markdown/code-tabs.html)，内部只能放代码块内容。 如果使用 [选项卡](https://theme-hope.vuejs.press/zh/guide/markdown/tabs.html)，内部会存在冗余空间，且体积较大。

![image](https://github.com/linxinrao/Shamrock/assets/96060102/cdb6eb3f-3ea8-4210-a9f6-1914cb2348ad)
![image](https://github.com/linxinrao/Shamrock/assets/96060102/76c53b36-8216-4b82-8c85-6b58dabd4ecc)

```
.vp-tabs {
  border: none
  // 去除边框
}
.vp-tabs {
  .vp-tabs-nav,.vp-tab{
    background: transparent !important;
    -webkit-backdrop-filter: blur(16px) !important;
    backdrop-filter: blur(16px) !important;
    // 设置背景模糊
  }
  * {
    margin: 0;
    // 去除margin
  }
  .language-json{
    margin: 0;
    // 去除代码框的margin
  }
}
```

**Comment by jinyu2022** [comment]
觉得还是太大可以把`padding: 0`加上，那样就彻底没有间距了

**Comment by jinyu2022** [comment]
如果觉得可以我晚上pr一个？

**Comment by RealHeart** [comment]
> 如果觉得可以我晚上pr一个？

你有时间也可以 我凌晨左右有时间
