### ISSUE TITLE
bug: 原生Android只能调起数字键盘输入回调地址

### ISSUE THREAD

**Issue by CDN18** [linxinrao/Shamrock#79]
**警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 确保您使用的是 [最新开发版本][actions-link] 的 Shamrock.
- [x] 确保您的问题尚未在 Issues 列表中提出.
- [x] 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

系统：Pixel Experience 13
输入法：GBoard

在输入回调地址时，调起的是只有数字的小键盘（123），之前的开发版还可以通过粘贴输入回调地址，现在粘贴也无法进行输入

### 复现 Bug

使用原生Android正常安装并打开输入框即可。

## 系统信息

- Shamrock 版本: `Shamrock-release-f6281f1392936d33ca300b63c411f5c9bb2731ca-ALL`
- Android 版本: `13.0`
- 设备的制造商和型号: `OnePlus 7 Pro`
- 设备的 CPU 架构: `arm64`

[actions-link]: https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml

**Comment by fuqiuluo** [comment]
在新版本将修复

**Comment by fuqiuluo** [comment]
https://github.com/linxinrao/Shamrock/actions/runs/6485153856
