### ISSUE TITLE
添加天气卡片消息

### ISSUE THREAD

**Issue by icarus-ai** [linxinrao/Shamrock#9]
`{`
`	"app"   : "com.tencent.weather",`
`	"desc"  : "天气",`
`	"view"  : "RichInfoView",`
`	"ver"   : "0.0.0.1",`
`	"prompt": "[应用]天气",`
`	"meta"  : {`
`		"richinfo":`
`		{`
`			"adcode" : "",`
`			"air"    : "5",`
`			"city"   : "天气测试",`
`			"date"   : "20210101",`
`			"max"    : "1",`
`			"min"    : "-1",`
`			"ts"     : "1635488302",`
`			"type"   : "205",`
`			"wind"   : "1"`
`		}`
`	}`
}`

adcode: code, // 地区代码 101251201

**Comment by icarus-ai** [comment]
type

`	"晴": "201",`
`	"云": "202",`
	"阴": "203",`
`	"雨": "204",`
`	"雪": "205",`
`	"雾": "206",`
`	"沙": "207",`
`	"尘": "207",`
`	"霾": "208",`

**Comment by fuqiuluo** [comment]
请求API：https://weather.mp.qq.com/page/poster?_wv=2&&_wwv=4&adcode=城市id

**Comment by fuqiuluo** [comment]
需要使用工具解析网页或者WebView加载html后使用js把数据取出。

**Comment by icarus-ai** [comment]
> 需要使用工具解析网页或者WebView加载html后使用js把数据取出。

See https://gitlab.com/mirai-bot/kos-plugin/-/blob/main/v1/tencent/weather.go

**Comment by fuqiuluo** [comment]
已经完成代码，正在制作cookie刷新。
