### ISSUE TITLE
bug: 发送图片有时报错：rich media transfer failed

### ISSUE THREAD

**Issue by foxdad** [linxinrao/Shamrock#98]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

连续发送图片的时候，间隔1-2秒的时候出现响应了 这个 
![a040ee7399bb677ae60024c172f4cabd](https://github.com/linxinrao/Shamrock/assets/48538835/52299f26-a915-4428-a612-ad0cc4c671f5)

请清晰地描述此 Bug 的具体表现，并提供错误日志。

### 复现 Bug

使用cq码的方式发送，这个是请求的日志
{"group_id":273260831,"message":"[CQ:image,file=https://pic1.imgdb.cn/item/6447f4c00d2dde57778ac949.jpg]"}

sk的响应，图片也没有发送
![a040ee7399bb677ae60024c172f4cabd](https://github.com/linxinrao/Shamrock/assets/48538835/4a342fc5-29ed-421e-b64d-bcc8668d6d6f)

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 1.0.4
- Android 版本: Android 9 
- 设备的制造商和型号:  
- 设备的 CPU 架构:

**Comment by fuqiuluo** [comment]
![image](https://github.com/linxinrao/Shamrock/assets/61898844/bb5d192e-ccc3-481d-ac47-0dcecf986f2e)

**Comment by fuqiuluo** [comment]
可以发送，无法复现
这个错误是因为上传失败导致

**Comment by foxdad** [comment]
> 可以发送，无法复现 这个错误是因为上传失败导致

尝试连续发送呢，
https://pic.imgdb.cn/item/6517f61bc458853aef53849f.png
https://pic.imgdb.cn/item/6517f077c458853aef510989.png
https://pic.imgdb.cn/item/6517f5cfc458853aef5375a4.png
https://pic.imgdb.cn/item/6517f063c458853aef5106db.jpg
https://pic.imgdb.cn/item/6517be7ac458853aef4517a6.png

大佬，你试试连续发送图，就会出现这种情况 
链接，你发送试试

**Comment by fuqiuluo** [comment]
无法复现

**Comment by SunshineboyZj** [comment]
+1，概率性出现
